"""add tmp_tbl

Revision ID: 1ce8d686620c
Revises: 52bd75d5d4cc
Create Date: 2022-12-15 03:42:53.391618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce8d686620c'
down_revision = '52bd75d5d4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_tmp', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_tmp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp_tbl')
    # ### end Alembic commands ###
