"""del tmp_tbl

Revision ID: 52bd75d5d4cc
Revises: c5fef4d8f48d
Create Date: 2022-12-15 03:35:44.127837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52bd75d5d4cc'
down_revision = 'c5fef4d8f48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmp_tbl', schema=None) as batch_op:
        batch_op.drop_index('name_tmp')

    op.drop_table('tmp_tbl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_tbl',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_tmp', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tmp_tbl', schema=None) as batch_op:
        batch_op.create_index('name_tmp', ['name_tmp'], unique=False)

    # ### end Alembic commands ###
