global:
  scrape_interval: 3s

  external_labels:
    monitor: "example-app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "flask"
    static_configs:
      - targets: ["192.168.51.7:5000"]
